local lexer = require("dry4lua.lexer")
local scope = require("dry4lua.scope")

local function extract(source)
  return scope.extract(lexer.tokenize(source))
end

test("scope: named function", function()
  local scopes = extract("function foo()\nend")
  assert_eq(#scopes, 1)
  assert_eq(scopes[1].name, "foo")
  assert_eq(scopes[1].start_line, 1)
  assert_eq(scopes[1].end_line, 2)
end)

test("scope: dotted and method names", function()
  assert_eq(extract("function a.b.c() end")[1].name, "a.b.c")
  assert_eq(extract("function a.b:c() end")[1].name, "a.b:c")
end)

test("scope: local function", function()
  assert_eq(extract("local function helper() end")[1].name, "helper")
end)

test("scope: anonymous function assigned to variable", function()
  local scopes = extract("local f = function()\nend")
  assert_eq(scopes[1].name, "anonymous@1")
end)

test("scope: immediately invoked anonymous function", function()
  local scopes = extract("(function()\nend)()")
  assert_eq(scopes[1].name, "anonymous@1")
end)

test("scope: nested functions are both extracted", function()
  local scopes = extract("function outer()\n  function inner()\n  end\nend")
  assert_eq(#scopes, 2)
  assert_eq(scopes[1].name, "inner")
  assert_eq(scopes[1].start_line, 2)
  assert_eq(scopes[1].end_line, 3)
  assert_eq(scopes[2].name, "outer")
  assert_eq(scopes[2].start_line, 1)
  assert_eq(scopes[2].end_line, 4)
end)

test("scope: if blocks do not swallow function end", function()
  local scopes = extract("function f()\n  if x then\n  end\nend")
  assert_eq(#scopes, 1)
  assert_eq(scopes[1].end_line, 4)
end)

test("scope: repeat until does not swallow function end", function()
  local scopes = extract("function f()\n  repeat\n  until x\nend")
  assert_eq(#scopes, 1)
  assert_eq(scopes[1].end_line, 4)
end)

test("scope: standalone do block does not swallow function end", function()
  local scopes = extract("function f()\n  do\n  end\nend")
  assert_eq(#scopes, 1)
  assert_eq(scopes[1].end_line, 4)
end)

test("scope: function containing a for loop is extracted", function()
  local scopes = extract("function f()\n  for i = 1, 10 do\n  end\nend")
  assert_eq(#scopes, 1)
  assert_eq(scopes[1].name, "f")
  assert_eq(scopes[1].end_line, 4)
end)

test("scope: function containing a while loop is extracted", function()
  local scopes = extract("function f()\n  while x do\n  end\nend")
  assert_eq(#scopes, 1)
  assert_eq(scopes[1].end_line, 4)
end)

test("scope: function containing a generic for loop is extracted", function()
  local scopes = extract("function f()\n  for k, v in pairs(t) do\n  end\nend")
  assert_eq(#scopes, 1)
  assert_eq(scopes[1].end_line, 4)
end)

test("scope: standalone do inside if still opens a block", function()
  local scopes = extract("function f()\n  if x then\n    do\n    end\n  end\nend")
  assert_eq(#scopes, 1)
  assert_eq(scopes[1].end_line, 6)
end)

test("scope: nested loops inside function", function()
  local scopes = extract("function f()\n  for i = 1, 10 do\n    while x do\n    end\n  end\nend")
  assert_eq(#scopes, 1)
  assert_eq(scopes[1].end_line, 6)
end)

test("scope: loop with function call in header", function()
  local scopes = extract("function f()\n  for k in (function() return t end)() do\n  end\nend")
  assert_eq(#scopes, 2)
  assert_eq(scopes[2].name, "f")
  assert_eq(scopes[2].end_line, 4)
end)

test("scope: repeat with nested while loop", function()
  local scopes = extract("function f()\n  repeat\n    while x do\n    end\n  until y\nend")
  assert_eq(#scopes, 1)
  assert_eq(scopes[1].end_line, 6)
end)

test("scope: positions span function keyword to end keyword", function()
  local source = "function f() end"
  local scopes = extract(source)
  assert_eq(scopes[1].start_pos, 1)
  assert_eq(scopes[1].end_pos, #source)
end)

test("scope: empty input yields no scopes", function()
  assert_eq(#extract(""), 0)
end)
